USE cyber_schema;

CREATE TABLE STATUS(
ID INT NOT NULL AUTO_INCREMENT,
DESCRIPTION VARCHAR(100) NOT NULL,
DATE_CREATED DATE NOT NULL,
DATE_MODIFIED DATE NOT NULL,
DATE_CEASED DATE,
MODIFIED_BY INT NOT NULL,
PRIMARY KEY(ID)
)ENGINE=InnoDB;

CREATE TABLE BUS(
ID INT NOT NULL AUTO_INCREMENT,
BUS_NUMBER VARCHAR(20) NOT NULL,
REGISTRATION_NO VARCHAR(20) NULL,
LICENSE_NO VARCHAR(20) NOT NULL,
ENGINE_NO VARCHAR(20) NOT NULL,
VIN_NO VARCHAR(20) NOT NULL,
GVM_KG INT NULL,
TARE VARCHAR(20) NULL,
MAKE VARCHAR(30) NOT NULL,
MODEL VARCHAR(30) NOT NULL,
CHASSIS_NO VARCHAR(50) NULL,
DESCRIPTION VARCHAR(200),
NO_OF_PERSON INT NOT NULL,
NO_OF_SEATED INT NOT NULL,
NO_OF_STANDING INT NOT NULL,
NO_OF_WHEEL_CHAIR INT NOT NULL,
DATE_OF_TEST DATE,
DATE_OF_EXPIRY DATE,
DATE_OF_FIRST_REGISTRATION DATE NOT NULL,
DATE_CREATED DATE NOT NULL,
DATE_MODIFIED DATE NOT NULL,
DATE_CEASED DATE,
MODIFIED_BY INT NOT NULL,
PRIMARY KEY(ID)
)ENGINE=InnoDB;

CREATE TABLE MECHANIC(
ID INT NOT NULL AUTO_INCREMENT,
TITLE VARCHAR(10) NOT NULL,
INTIALS VARCHAR(5) NOT NULL,
EMP_NO  VARCHAR(20) NOT NULL,
IDENTITY_NO VARCHAR(20) NULL,
PASSPORT_NO VARCHAR(20) NULL,
FIRSTNAME  VARCHAR(50) NOT NULL,
LASTNAME  VARCHAR(50) NOT NULL,
EMAIL  VARCHAR(60) NULL,
TEL VARCHAR(10) NULL,
CELL VARCHAR(10) NULL,
DATE_CREATED DATE NOT NULL,
DATE_MODIFIED DATE NOT NULL,
DATE_CEASED DATE,
MODIFIED_BY INT NOT NULL,
PRIMARY KEY(ID)
)ENGINE=InnoDB;

CREATE TABLE ASSIGNED_CALL(
ID INT NOT NULL AUTO_INCREMENT,
BUS_ID INT NOT NULL,
MECHANIC_ID INT NOT NULL,
STATUS_ID INT NOT NULL,
DATE_OPENED DATE NOT NULL,
DATE_CLOSED DATE NOT NULL,
DATE_CREATED DATE NOT NULL,
DATE_MODIFIED DATE NOT NULL,
DATE_CEASED DATE,
MODIFIED_BY INT NOT NULL,
PRIMARY KEY(ID),
FOREIGN KEY (STATUS_ID) REFERENCES STATUS(ID),
FOREIGN KEY (BUS_ID) REFERENCES BUS(ID),
FOREIGN KEY (MECHANIC_ID) REFERENCES MECHANIC(ID)
)ENGINE=InnoDB;

CREATE TABLE LOGGED_CALL(
ID INT NOT NULL AUTO_INCREMENT,
BUS_ID INT NOT NULL,
FAULT_DESCRIPTION VARCHAR(200) NOT NULL,
DRIVER_NAME VARCHAR(50) NOT NULL,
DATE_CREATED DATE NOT NULL,
DATE_MODIFIED DATE NOT NULL,
DATE_CEASED DATE,
MODIFIED_BY INT NOT NULL,
PRIMARY KEY(ID),
FOREIGN KEY(BUS_ID) REFERENCES BUS(ID)
)ENGINE=InnoDB;

CREATE TABLE SERVICE_HISTORY(
ID INT NOT NULL AUTO_INCREMENT,
BUS_ID INT NOT NULL,
MECHANIC_ID INT NOT NULL,
JOB_CARD_NO VARCHAR(100) NOT NULL,
DESCRIPTION VARCHAR(200) NULL,
LAST_SERVICE_KM VARCHAR(100) NULL,
DATE_CREATED DATE NOT NULL,
DATE_LOGGED DATE NOT NULL,
DATE_OPEN DATE NOT NULL,
DATE_CLOSED DATE NOT NULL,
MODIFIED_BY INT NOT NULL,
PRIMARY KEY(ID),
FOREIGN KEY(BUS_ID) REFERENCES BUS(ID),
FOREIGN KEY(MECHANIC_ID) REFERENCES MECHANIC(ID)
)ENGINE=InnoDB;

CREATE TABLE DEVICE(
ID INT NOT NULL AUTO_INCREMENT,
NAME VARCHAR(30) NOT NULL,
IMEI_NO VARCHAR(100) NOT NULL,
CELL VARCHAR(10) NULL,
SIM_NO VARCHAR(100) NULL,
DATE_CREATED DATE NOT NULL,
DATE_MODIFIED DATE NOT NULL,
DATE_CEASED DATE,
MODIFIED_BY INT NOT NULL,
PRIMARY KEY(ID)
)ENGINE=InnoDB;

CREATE TABLE MECHANIC_DEVICE(
ID INT NOT NULL AUTO_INCREMENT,
MECHANIC_ID INT NOT NULL,
DEVICE_ID INT NOT NULL,
DATE_CREATED DATE NOT NULL,
DATE_MODIFIED DATE NOT NULL,
DATE_CEASED DATE,
MODIFIED_BY INT NOT NULL,
PRIMARY KEY(ID),
FOREIGN KEY (MECHANIC_ID) REFERENCES MECHANIC(ID),
FOREIGN KEY (DEVICE_ID) REFERENCES DEVICE(ID)
)ENGINE=InnoDB;

CREATE TABLE ADDRESS(
ID INT NOT NULL AUTO_INCREMENT,
SUBURB VARCHAR(20) NOT NULL,
CITY VARCHAR(20) NOT NULL,
PROVINCE VARCHAR(20) NOT NULL,
POSTAL_CODE INT NOT NULL,
MECHANIC_ID INT NOT NULL,
DATE_CREATED DATE NOT NULL,
DATE_MODIFIED DATE NOT NULL,
DATE_CEASED DATE,
MODIFIED_BY INT NOT NULL,
PRIMARY KEY(ID)
)ENGINE=InnoDB;

CREATE TABLE ROLE(
ID INT NOT NULL AUTO_INCREMENT,
NAME VARCHAR(30) NOT NULL,
DESCRIPTION VARCHAR(100),
DATE_CREATED DATE NOT NULL,
DATE_MODIFIED DATE NOT NULL,
DATE_CEASED DATE,
MODIFIED_BY INT NOT NULL,
PRIMARY KEY(ID)
)ENGINE=InnoDB;

CREATE TABLE MENU(
ID INT NOT NULL AUTO_INCREMENT,
NAME VARCHAR(15) NOT NULL,
SEQ INT,
DATE_CREATED DATE NOT NULL,
DATE_MODIFIED DATE NOT NULL,
DATE_CEASED DATE,
MODIFIED_BY INT NOT NULL,
PRIMARY KEY(ID)
)ENGINE=InnoDB;

CREATE TABLE USERS(
ID INT NOT NULL AUTO_INCREMENT,
USERNAME VARCHAR(50),
FIRSTNAME VARCHAR(50),
DESCRIPTION VARCHAR(100),
TEL VARCHAR(10) NULL,
CELL VARCHAR(10) NULL,
DATE_CREATED DATE NOT NULL,
DATE_MODIFIED DATE NOT NULL,
DATE_CEASED DATE,
MODIFIED_BY INT NOT NULL,
PRIMARY KEY(ID)
)ENGINE=InnoDB;

CREATE TABLE ROLE_MENU(
ID INT NOT NULL AUTO_INCREMENT,
ROLE_ID INT NOT NULL,
MENU_ID INT NOT NULL,
DATE_CREATED DATE NOT NULL,
DATE_MODIFIED DATE NOT NULL,
DATE_CEASED DATE,
MODIFIED_BY INT NOT NULL,
FOREIGN KEY (ROLE_ID) REFERENCES ROLE(ID),
FOREIGN KEY (MENU_ID) REFERENCES MENU(ID),
PRIMARY KEY(ID)
)ENGINE=InnoDB;


CREATE TABLE USER_ROLE(
ID INT NOT NULL AUTO_INCREMENT,
ROLE_ID INT NOT NULL,
USER_ID INT NOT NULL,
DATE_CREATED DATE NOT NULL,
DATE_MODIFIED DATE NOT NULL,
DATE_CEASED DATE,
MODIFIED_BY INT NOT NULL,
PRIMARY KEY(ID),
FOREIGN KEY (ROLE_ID) REFERENCES ROLE(ID),
FOREIGN KEY (USER_ID) REFERENCES USERS(ID)
)ENGINE=InnoDB;